name       : libserialport
version    : 0.1.1
release    : 2
source     :
    - http://sigrok.org/download/source/libserialport/libserialport-0.1.1.tar.gz : 4a2af9d9c3ff488e92fb75b4ba38b35bcf9b8a66df04773eba2a7bbf1fa7529d
license    : LGPL-3.0
component  : programming.library
summary    : cross-platform library for accessing serial ports
description: |
    libserialport is a minimal library written in C that is intended to take care of the OS-specific details when writing software that uses serial ports.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
